version: '3.9'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-airflights}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    ports: ["5432:5432"]
    volumes:
      - pg-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-airflights}"]
      interval: 5s
      timeout: 3s
      retries: 20
    container_name: postgres

  # ===== INFRASTRUCTURE =====
  eureka-server:
    build:
      context: ./eureka-server
      dockerfile: Dockerfile
    ports: ["8761:8761", "5005:5005"]
    depends_on: [postgres]
    environment:
      SPRING_PROFILES_ACTIVE: docker
      JAVA_TOOL_OPTIONS: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:8761/actuator/health" ]
      interval: 5s
      timeout: 3s
      retries: 20
    container_name: eureka-server

  config-server:
    build:
      context: ./config-server
      dockerfile: Dockerfile
    ports: ["9991:9991", "5006:5006"]
    depends_on:
      eureka-server:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: native
      SPRING_CLOUD_CONFIG_SERVER_NATIVE_SEARCH_LOCATIONS: file:/cfgs
      JAVA_TOOL_OPTIONS: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5006
    volumes:
      - ./cfgs/config-server-main:/cfgs:ro
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9991/actuator/health"]
      interval: 5s
      timeout: 3s
      retries: 20
    container_name: config-server

  gateway-server:
    build:
      context: ./gateway-server
      dockerfile: Dockerfile
    ports: ["8080:8080", "5007:5007"]
    depends_on:
      config-server:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: dev
      JAVA_TOOL_OPTIONS: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5007
    container_name: gateway-server

  # ===== MICROSERVICES =====
  airline-service:
    build:
      context: ./airline-service
      dockerfile: Dockerfile
    depends_on:
      config-server:
        condition: service_healthy
    ports: ["5008:5008"]
    environment:
      SPRING_PROFILES_ACTIVE: dev
      JAVA_TOOL_OPTIONS: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5008
    container_name: airline-service

  airport-service:
    build:
      context: ./airport-service
      dockerfile: Dockerfile
    depends_on:
      config-server:
        condition: service_healthy
    ports: ["5009:5009"]
    environment:
      SPRING_PROFILES_ACTIVE: dev
      JAVA_TOOL_OPTIONS: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5009
    container_name: airport-service

  booking-service:
    build:
      context: ./booking-service
      dockerfile: Dockerfile
    depends_on:
      config-server:
        condition: service_healthy
    ports: [ "5010:5010" ]
    environment:
      SPRING_PROFILES_ACTIVE: dev
      JAVA_TOOL_OPTIONS: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5010
    container_name: booking-service

  flight-service:
    build:
      context: ./flight-service
      dockerfile: Dockerfile
    depends_on:
      config-server:
        condition: service_healthy
    ports: [ "5011:5011" ]
    environment:
      SPRING_PROFILES_ACTIVE: dev
      JAVA_TOOL_OPTIONS: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5011
    container_name: flight-service

  passenger-service:
    build:
      context: ./passenger-service
      dockerfile: Dockerfile
    depends_on:
      config-server:
        condition: service_healthy
    ports: [ "5012:5012" ]
    environment:
      SPRING_PROFILES_ACTIVE: dev
      JAVA_TOOL_OPTIONS: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5012
    container_name: passenger-service

  restrictedzone-service:
    build:
      context: ./restrictedzone-service
      dockerfile: Dockerfile
    depends_on:
      config-server:
        condition: service_healthy
    ports: [ "5013:5013" ]
    environment:
      SPRING_PROFILES_ACTIVE: dev
      JAVA_TOOL_OPTIONS: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5013
    container_name: restrictedzone-service

  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    depends_on:
      config-server:
        condition: service_healthy
    ports: [ "5014:5014" ]
    environment:
      SPRING_PROFILES_ACTIVE: dev
      AUTH_BOOTSTRAP_USERNAME: admin
      AUTH_BOOTSTRAP_EMAIL: admin@itmo.ru
      AUTH_BOOTSTRAP_PASSWORD: 1234
      JAVA_TOOL_OPTIONS: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5014
    container_name: auth-service

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    volumes:
      - pgadmin_data:/var/lib/pgadmin
volumes:
  pg-data:
  pgadmin_data:
