spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/airline_db
        username: airline_user
        password: airline_pass
    jpa:
        hibernate:
            ddl-auto: validate
        properties:
            hibernate:
                "[format_sql]": true
                dialect: org.hibernate.dialect.PostgreSQLDialect
    flyway:
        enabled: true
        locations: classpath:db/migrations
    jackson:
        property-naming-strategy: SNAKE_CASE
        default-property-inclusion: NON_NULL
        


server:
    port: 8080