spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/airline_db
        username: airline_user
        password: airline_pass
    jpa:
    hibernate:
        ddl-auto: validate
    properties:
        hibernate:
            format_sql: true
            dialect: org.hibernate.dialect.PostgreSQLDialect
    flyway:
        enabled: true


server:
    port: 8080